config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations', passwords: 'users/passwords', registrations: 'users/registrations', sessions: 'users/sessions', unlocks: 'users/unlocks' }
  root 'home#index'

  authenticate :user do
    get '/search', to: 'search#search'

    resources :players do
      resources :player_notes
    end
    resources :high_school_teams
    resources :club_teams
    resources :tournaments
    resources :fields
    resources :games, only: [:new, :show, :edit, :update]
    resources :player_lists
    resources :exports, only: [:new, :create]
  end
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_one :tournament_director, dependent: :destroy
  has_many :games, inverse_of: :tournament, dependent: :destroy

  accepts_nested_attributes_for :tournament_director, allow_destroy: true
  accepts_nested_attributes_for :games, allow_destroy: true

  def self.search(query)
    if query
      where("lower(name) LIKE ?", "%#{query.downcase}%")
    else
      all
    end
  end

  def self.sorted_tournaments(sort_column, sort_direction)
    sorted_tournaments = nil

    if sort_column === "dates"
      tournaments_with_attr, tournaments_without_attr = self.all.partition { |t| !t.date_range.empty? }
      tournaments_with_attr = tournaments_with_attr.sort do |a,b|
        a.date_range <=> b.date_range
      end
      tournaments_with_attr.reverse! if sort_direction === "asc"
      sorted_tournaments = tournaments_with_attr + tournaments_without_attr
    elsif sort_column === "location"
      tournaments_with_attr, tournaments_without_attr = self.all.partition { |t| !t.location.empty? }
      tournaments_with_attr = tournaments_with_attr.sort do |a,b|
        a.location <=> b.location
      end
      tournaments_with_attr.reverse! if sort_direction === "asc"
      sorted_tournaments = tournaments_with_attr + tournaments_without_attr
    else
      tournaments_with_attr = self.where("#{sort_column} IS NOT NULL")
      tournaments_without_attr = self.where("#{sort_column} IS NULL")
      sorted_tournaments = tournaments_with_attr.order("#{sort_column} #{sort_direction}") + tournaments_without_attr
    end

    return sorted_tournaments
  end

  def self.filter_options
    return {
      locations: self.location_filter_options,
    }
  end

  def self.location_filter_options
    locations = []

    self.all.each do |tournament|
      if !locations.include? tournament.location
        locations << tournament.location
      end
    end

    return locations.sort { |a,b| a.name <=> b.name }
  end

  def passes_through_filters(filters)
    return (
      passes_through_location_filters(filters[:location_filters]) &&
      passes_through_earliest_start_date_filters(filters[:earliest_start_date]) &&
      passes_through_latest_start_date_filters(filters[:latest_start_date])
    )
  end

  def passes_through_location_filters(location_filters)
    return location_filters.include? self.location
  end

  def passes_through_earliest_start_date_filters(earliest_start_date)
    if self.earliest_date === nil || !earliest_start_date || earliest_start_date.length === 0
      return true
    end

    return self.earliest_date >= Date.parse(earliest_start_date)
  end

  def passes_through_latest_start_date_filters(latest_start_date)
    if self.earliest_date === nil || !latest_start_date || latest_start_date.length === 0
      return true
    end

    return self.earliest_date <= Date.parse(latest_start_date)
  end

  def games?
    return (games && games.length && games.length > 0)
  end

  def date_range
    if !games?
      return ""
    end

    return "#{earliest_date.to_formatted_s(:long)} - #{earliest_date.to_formatted_s(:long)}"
  end

  def location
    if (!games?)
      return ""
    end

    return games.first.field.location
  end

  def earliest_date
    earliest = nil

    self.games.each do |game|
      if game.date
        if !earliest
          earliest = game.date
        elsif game.date < earliest
          earliest = game.date
        end
      end
    end

    return earliest
  end

  def latest_date
    latest = nil

    self.games.each do |game|
      if !latest
        latest = game.date
      elsif game.date > latest
        latest = game.date
      end
    end

    return latest
  end

  def sorted_games(sort_column, sort_direction)
    if sort_column === "team_one"
      teams_with_attr = games.where("team_one_id IS NOT NULL")
      teams_without_attr = games.where("team_one_id IS NULL")

      return teams_with_attr.joins("INNER JOIN teams ON teams.id = games.team_one_id").order("teams.name #{sort_direction}") + teams_without_attr
    elsif sort_column === "team_two"
      teams_with_attr = games.where("team_two_id IS NOT NULL")
      teams_without_attr = games.where("team_two_id IS NULL")

      return teams_with_attr.joins("INNER JOIN teams ON teams.id = games.team_two_id").order("teams.name #{sort_direction}") + teams_without_attr
    elsif sort_column === "field"
      teams_with_attr = games.where("field_id IS NOT NULL")
      teams_without_attr = games.where("field_id IS NULL")

      return teams_with_attr.left_joins(:field).order("fields.name #{sort_direction}") + teams_without_attr
    else
      games_with_attr = games.where("#{sort_column} IS NOT NULL")
      games_without_attr = games.where("#{sort_column} IS NULL")

      return games_with_attr.order("#{sort_column} #{sort_direction}") + games_without_attr
    end
  end

  def filter_options(current_user)
    result = {}

    result[:player_lists] = get_player_lists_for_filter_options(current_user.player_lists)
    result[:teams] = get_teams_for_filter_options(self.games)
    result[:players] = get_players_for_filter_options(result[:teams])
    result[:dates] = get_dates_for_filter_options(self.games)
    result[:fields] = get_fields_for_filter_options(self.games)

    return result
  end

  def get_player_lists_for_filter_options(player_lists)
    return player_lists.sort { |a,b| a.name <=> b.name }
  end

  def get_players_for_filter_options(teams)
    players = []

    teams.each do |team|
      team.players.each do |player|
        players << player if !players.include?(player)
      end
    end

    return players.sort { |a,b| a.first_name <=> b.first_name }
  end

  def get_teams_for_filter_options(games)
    teams = []

    games.each do |game|
      teams << game.team_one if !teams.include?(game.team_one)
      teams << game.team_two if !teams.include?(game.team_two)
    end

    return teams.sort { |a,b| a.name <=> b.name }
  end

  def get_dates_for_filter_options(games)
    dates = []

    games.each do |game|
      dates << game.date if (!dates.include?(game.date) && game.date)
    end

    return dates.sort { |a,b| a <=> b }
  end

  def get_fields_for_filter_options(games)
    fields = []

    games.each do |game|
      fields << game.field if !fields.include?(game.field)
    end

    return fields.sort { |a,b| a.name <=> b.name }
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :authorize_user, except: [:index, :show]
  helper_method :sort_column, :sort_direction, :filter_params

  def index
    @filter_options = Tournament.filter_options
    @filters_to_apply = filter_params && !filter_params.empty?
    @tournaments = Tournament.sorted_tournaments(sort_column, sort_direction)
    @tournaments = @filters_to_apply ? get_filtered_tournaments(@tournaments, filter_params) : @tournaments
  end

  def show
    index_of_first_game = (page * Game.ITEMS_PER_PAGE) - Game.ITEMS_PER_PAGE
    index_of_last_game = page * Game.ITEMS_PER_PAGE

    @tournament = Tournament.find(params[:id])
    @filter_options = @tournament.filter_options(current_user)
    @filters_to_apply = filter_params && !filter_params.empty?
    @games = @tournament.sorted_games(sort_column, sort_direction)
    @games = @filters_to_apply ? get_filtered_games(@games, filter_params) : @games
    @num_filtered_games = @games.length
    @curr_page = page
    @games = @games[index_of_first_game...index_of_last_game]
  end

  def new
    @tournament = Tournament.new
    @tournament.tournament_director = TournamentDirector.new
    @tournament.tournament_director.address = Address.new
  end

  def create
    @tournament = Tournament.new(tournament_params)

    if @tournament.save
      redirect_to @tournament
    else
      @tournament.errors.full_messages.each do |message|
        puts message
      end
      render 'new'
    end
  end

  def edit
    @tournament = Tournament.find(params[:id])
  end

  def update
    @tournament = Tournament.find(params[:id])

    if @tournament.update(tournament_params)
      redirect_to @tournament
    else
      render 'edit'
    end
  end

  def destroy
    @tournament = Tournament.find(params[:id])
    @tournament.destroy

    redirect_to tournaments_path
  end

  private
    def tournament_params
      params
        .require(:tournament)
        .permit(:id, :commit, :name,
          tournament_director_attributes: [:id, :first_name, :middle_name, :last_name, :email, :phone_number, address_attributes: [ :id, :line_one, :line_two, :city, :state, :zip ]],
          games_attributes: [:id, :_destroy, :team_one_id, :team_two_id, :field_id, :field_number, :date, :start_time]
        )
    end

    def sort_column
      if params[:action] === "index"
        return %w[name dates location].include?(params[:sort]) ? params[:sort] : "name"
      elsif params[:action] === "show"
        return %w[id team_one team_two date start_time field].include?(params[:sort]) ? params[:sort] : "date"
      end
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def filter_params
      params.permit(:sort, :direction, :earliest_start_date, :latest_start_date, :earliest_start_time, :latest_start_time, :commit, :id, location_filters: [], player_list_filters: [], player_filters: [], team_filters: [], date_filters: [], field_filters: []).except(:id, :commit, :sort, :direction)
    end

    def get_filtered_tournaments(tournaments, filters)
      return tournaments.filter do |tournament|
        tournament.passes_through_filters(filters)
      end
    end

    def get_filtered_games(games, filters)
      return games.filter do |game|
        game.passes_through_filters(filters)
      end
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_with model: @tournament, class: 'tournament-form' do |f| %>
  <section class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </section>

  <section class="card">
    <section class="card-header">
      Tournament Director
    </section>
    <section class="card-body">
      <%= f.fields_for :tournament_director do |ff| %>
        <section class="form-group">
          <%= ff.label :first_name %>
          <%= ff.text_field :first_name, class: "form-control" %>
        </section>
        <section class="form-group">
          <%= ff.label :middle_name %>
          <%= ff.text_field :middle_name, class: "form-control" %>
        </section>
        <section class="form-group">
          <%= ff.label :last_name %>
          <%= ff.text_field :last_name, class: "form-control" %>
        </section>
        <section class="form-group">
          <%= ff.label :email %>
          <%= ff.email_field :email, class: "form-control" %>
        </section>
        <section class="form-group">
          <%= ff.label :phone_number %>
          <%= ff.phone_field :phone_number, class: "form-control" %>
        </section>
        <section class="card">
          <section class="card-header">
            Address
          </section>
          <section class="card-body">
            <%= render "shared/address_form", f: ff %>
          </section>
        </section>
      <% end %>
    </section>
  </section>

  <section class="games">
    <%= f.fields_for :games do |game| %>
      <%= render 'game_fields', f: game %>
    <% end %>
  </section>
  <p>
    <%= link_to_add_association "Add game", f, :games,
      data: {
        association_insertion_node: '.games',
        association_insertion_method: :append
      },
      class: "btn btn-light"
    %>
  </p>

  <%= f.submit nil, class: "btn btn-primary" %>
<% end %>

app/views/tournaments/_game_fields.html.erb
<section class="nested-fields card">
  <section class="card-header">
    Game
    <%= link_to_remove_association sanitize("&times;"), f, class: "close" %>
  </section>
  <section class="card-body">
    <%= render "games/form_fields", { f: f, game: f.object } %>
  </section>
</section>

app/views/tournaments/edit.html.erb
<h1 class="page-header">Edit tournament</h1>

<%= render 'form' %>

app/views/tournaments/index.html.erb
<h1 class="page-header">Tournaments</h1>

<p><%= link_to "Create a new tournament", new_tournament_path, class: "btn btn-primary" if is_admin? %></p>

<section class="row">
  <section class="col-lg-3">
    <section class="card bg-light filters">
      <section class="card-header">
        Filters
      </section>
      <section class="card-body">
        <%= form_with url: tournaments_path, method: :get, local: true do |f| %>
          <%= hidden_field_tag 'sort', params[:sort] if params[:sort] %>
          <%= hidden_field_tag 'direction', params[:direction] if params[:direction] %>
          <%= hidden_field_tag 'page', params[:page] if params[:page] %>
          <section class="filter-category">
            <span>Approximate locations</span>
            <% @filter_options[:locations].each do |location| %>
              <section class="form-check">
                <label class="form-check-label">
                  <%= f.check_box "location_filters[]", { class: "form-check-input", checked: !@filters_to_apply || params[:location_filters].try(:include?, location) }, location, nil %>
                  <%= location %>
                </label>
              </section>
            <% end %>
          </section>
          <section class="filter-category">
            <section class="form-group">
              <%= f.label :earliest_start_date, class: "col-header" %>
              <%= f.date_field :earliest_start_date, value: params[:earliest_start_date], class: "form-control" %>
            </section>
          </section>
          <section class="filter-category">
            <section class="form-group">
              <%= f.label :latest_start_date, class: "col-header" %>
              <%= f.date_field :latest_start_date, value: params[:latest_start_date], class: "form-control" %>
            </section>
          </section>
          <hr>
          <%= submit_tag "Apply filters", class: "btn btn-secondary btn-block" %>
        <% end %>
      </section>
    </section>
  </section>
  <section class="col-lg-9">
    <table class="table table-hover">
      <tr>
        <th><%= sortable "name", sort_column, sort_direction %></th>
        <th><%= sortable "dates", sort_column, sort_direction %></th>
        <th><%= sortable "location", sort_column, sort_direction, "Approximate location" %></th>
        <% if is_admin? %>
          <th>Edit</th>
          <th>Delete</th>
        <% end %>
      </tr>
      <% @tournaments.each do |tournament| %>
        <tr>
          <td><%= link_to tournament.name, tournament_path(tournament) %></td>
          <td><%= tournament.date_range %></td>
          <td><%= tournament.location %></td>
          <% if is_admin? %>
            <td><%= link_to "Edit", edit_tournament_path(tournament) %></td>
            <td><%= link_to 'Delete', tournament_path(tournament),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </section>
</section>

app/views/tournaments/new.html.erb
<h1 class="page-header">Create a tournament</h1>

<%= render 'form' %>

app/views/tournaments/show.html.erb
<h1 class="page-header">Tournament: <%= @tournament.name %></h1>

<section class="row">
  <section class="col-lg-3">
    <section class="card bg-light filters">
      <section class="card-header">
        Filters
      </section>
      <section class="card-body">
        <%= form_with url: tournament_path(@tournament), method: :get, local: true do |f| %>
          <%= hidden_field_tag 'sort', params[:sort] if params[:sort] %>
          <%= hidden_field_tag 'direction', params[:direction] if params[:direction] %>
          <%= hidden_field_tag 'page', params[:page] if params[:page] %>
          <% if !@filter_options[:player_lists].empty? %>
            <section class="filter-category filter-category-fixed-height">
              <span>Players lists:</span>
              <% @filter_options[:player_lists].each do |player_list| %>
                <section class="form-check">
                  <label class="form-check-label">
                    <%= f.check_box "player_list_filters[]", { class: "form-check-input", checked: params[:player_list_filters].try(:include?, player_list.id.to_s) }, player_list.id, nil %>
                    <%= player_list.name %>
                  </label>
                </section>
              <% end %>
            </section>
          <% end %>
          <section class="filter-category filter-category-fixed-height">
            <span>Players:</span>
            <% @filter_options[:players].each do |player| %>
              <section class="form-check">
                <label class="form-check-label">
                  <%= f.check_box "player_filters[]", { class: "form-check-input", checked: !@filters_to_apply || params[:player_filters].try(:include?, player.id.to_s) }, player.id, nil %>
                  <%= player.full_name %>
                </label>
              </section>
            <% end %>
          </section>
          <section class="filter-category filter-category-fixed-height">
            <span>Teams:</span>
            <% @filter_options[:teams].each do |team| %>
              <section class="form-check">
                <label class="form-check-label">
                  <%= f.check_box "team_filters[]", { class: "form-check-input", checked: !@filters_to_apply || params[:team_filters].try(:include?, team.id.to_s) }, team.id, nil %>
                  <%= team.full_name %>
                </label>
              </section>
            <% end %>
          </section>
          <section class="filter-category">
            <span>Dates:</span>
            <% @filter_options[:dates].each do |date| %>
              <section class="form-check">
                <label class="form-check-label">
                  <%= f.check_box "date_filters[]", { class: "form-check-input", checked: !@filters_to_apply || params[:date_filters].try(:include?, date.to_s) }, date, nil %>
                  <%= date.to_formatted_s(:long) %>
                </label>
              </section>
            <% end %>
          </section>
          <section class="filter-category">
            <span>Fields:</span>
            <% @filter_options[:fields].each do |field| %>
              <section class="form-check">
                <label class="form-check-label">
                  <%= f.check_box "field_filters[]", { class: "form-check-input", checked: !@filters_to_apply || params[:field_filters].try(:include?, field.id.to_s) }, field.id, nil %>
                  <%= field.name %>
                </label>
              </section>
            <% end %>
          </section>
          <section class="filter-category">
            <span>Time:</span>
            <section class="form-group">
              <%= f.label :earliest_start_time %>
              <%= f.time_field :earliest_start_time, value: params[:earliest_start_time], class: "form-control" %>
            </section>
            <section class="form-group">
              <%= f.label :latest_start_time %>
              <%= f.time_field :latest_start_time, value: params[:latest_start_time], class: "form-control" %>
            </section>
          </section>
          <hr>
          <%= submit_tag "Apply filters", class: "btn btn-secondary btn-block" %>
        <% end %>
      </section>
    </section>
  </section>
  <section class="col-lg-9">
    <section class="card">
      <section class="card-header">
        Director
      </section>
      <section class="card-body">
        <%= render "shared/person", person: @tournament.tournament_director %>
        <%= render "shared/address", address: @tournament.tournament_director.address %>
      </section>
    </section>
    <table class="table">
      <thead>
        <tr>
          <th><%= sortable "id", sort_column, sort_direction, "Game ID" %></th>
          <th><%= sortable "team_one", sort_column, sort_direction%></th>
          <th><%= sortable "team_two", sort_column, sort_direction %></th>
          <th><%= sortable "date", sort_column, sort_direction %></th>
          <th><%= sortable "start_time", sort_column, sort_direction %></th>
          <th><%= sortable "field", sort_column, sort_direction %></th>
          <th>Field number</th>
        </tr>
      </thead>
      <tbody>
        <% @games.each do |game| %>
          <tr>
            <td><%= link_to game.id, game_path(game) %></td>
            <td><%= link_to game.team_one.full_name, team_path(game.team_one) %></td>
            <td><%= link_to game.team_two.full_name, team_path(game.team_two) %></td>
            <td><%= game.date.to_formatted_s(:long) if game.date %></td>
            <td><%= game.start_time.strftime("%I:%M %p") if game.start_time %></td>
            <td><%= link_to game.field.name, field_path(game.field) if game.field %></td>
            <td><%= game.field_number if game.try(:field_number) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= render "shared/pagination", curr_page: @curr_page, num_pages: (@num_filtered_games / Game.ITEMS_PER_PAGE).ceil %>
  </section>
</section>

<%= link_to 'Edit', edit_tournament_path if is_admin? %>