config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations', passwords: 'users/passwords', registrations: 'users/registrations', sessions: 'users/sessions', unlocks: 'users/unlocks' }
  root 'home#index'

  authenticate :user do
    get '/search', to: 'search#search'

    resources :players do
      resources :player_notes
    end
    resources :high_school_teams
    resources :club_teams
    resources :tournaments
    resources :fields
    resources :games, only: [:new, :show, :edit, :update]
    resources :player_lists
    resources :exports, only: [:new, :create]
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :high_school_team, class_name: "Team", optional: true
  belongs_to :club_team, class_name: "Team", optional: true
  has_one :address, as: :addressable, dependent: :destroy
  has_many :player_list_players
  has_many :player_lists, through: :player_list_players
  has_many :player_notes, dependent: :destroy

  accepts_nested_attributes_for :address, allow_destroy: true
  has_rich_text :notes

  def self.search(query)
    if query
      where("
        lower(first_name) LIKE ? OR
        lower(last_name) LIKE ?
      ", "%#{query.downcase}%", "%#{query.downcase}%")
    else
      all
    end
  end

  def self.sorted_players(sort_column, sort_direction, players = self.all)
    sorted_players = nil

    if sort_column === "class_year"
      class_years = ["5th grade", "6th grade", "7th grade", "8th grade", "Freshman", "Sophomore", "Junior", "Senior"]
      players_with_attr = players.where("#{sort_column} IS NOT NULL")
      players_without_attr = players.where("#{sort_column} IS NULL")
      players_with_attr = players_with_attr.select(&:class_year).sort do |a,b|
        class_years.index(a.class_year) <=> class_years.index(b.class_year)
      end
      players_with_attr.reverse! if sort_direction === "desc"
      sorted_players = players_with_attr + players_without_attr
    elsif sort_column === "high_school_team"
      players_with_attr = players.where("high_school_team_id IS NOT NULL")
      players_without_attr = players.where("high_school_team_id IS NULL")
      sorted_players = players_with_attr.joins("INNER JOIN teams ON teams.id = players.high_school_team_id").order("teams.name #{sort_direction}") + players_without_attr
    elsif sort_column === "club_team"
      players_with_attr = players.where("club_team_id IS NOT NULL")
      players_without_attr = players.where("club_team_id IS NULL")
      sorted_players = players_with_attr.joins("INNER JOIN teams ON teams.id = players.club_team_id").order("teams.name #{sort_direction}") + players_without_attr
    else
      players_with_attr = players.where("#{sort_column} IS NOT NULL")
      players_without_attr = players.where("#{sort_column} IS NULL")
      sorted_players = players_with_attr.order("#{sort_column} #{sort_direction}") + players_without_attr
    end

    return sorted_players
  end

  def self.filter_options(players = self.all)
    return {
      high_school_teams: self.high_school_teams_filter_options(players),
      club_teams: self.club_teams_filter_options(players),
      class_years: self.class_years_filter_options(players)
    }
  end

  def self.high_school_teams_filter_options(players)
    high_school_teams = []

    players.each do |player|
      if !high_school_teams.include? player.high_school_team
        high_school_teams << player.high_school_team
      end
    end
    high_school_teams = high_school_teams.filter { |t| !!t }

    return high_school_teams.sort { |a,b| a.name <=> b.name }
  end

  def self.club_teams_filter_options(players)
    club_teams = []

    players.each do |player|
      if !club_teams.include? player.club_team
        club_teams << player.club_team
      end
    end
    club_teams = club_teams.filter { |t| !!t }

    return club_teams.sort { |a,b| a.name <=> b.name }
  end

  def self.class_years_filter_options(players)
    order = ["Senior", "Junior", "Sophomore", "Freshman", "8th grade", "7th grade", "6th grade", "5th grade"]
    class_years = []

    players.each do |player|
      if !class_years.include?(player.class_year) && player.class_year && !player.class_year.empty?
        class_years << player.class_year
      end
    end

    return class_years.sort { |a,b| order.index(a) <=> order.index(b) }
  end

  def self.ids_with_my_notes(current_user)
    self.all.filter { |player|
      !!player.current_user_notes(current_user)
    }.map { |player|
      player.id
    }
  end

  def passes_through_filters(filters)
    return (
      passes_through_height_filters(filters[:shortest_feet], filters[:shortest_inches], filters[:tallest_feet], filters[:tallest_inches]) &&
      passes_through_weight_filters(filters[:lightest], filters[:heaviest]) &&
      passes_through_high_school_team_filters(filters[:high_school_team_filters]) &&
      passes_through_club_team_filters(filters[:club_team_filters]) &&
      passes_through_class_year_filters(filters[:class_year_filters]) &&
      passes_through_gpa_filters(filters[:smallest_gpa], filters[:largest_gpa])
    )
  end

  def passes_through_height_filters(shortest_feet, shortest_inches, tallest_feet, tallest_inches)
    if !self.height
      return true
    end

    if (!shortest_feet.empty? && !shortest_inches.empty?) && (!tallest_feet.empty? && !tallest_inches.empty?)
      shortest_height_allowed_in_inches = (shortest_feet.to_f * 12) + shortest_inches.to_f
      tallest_height_allowed_in_inches = (tallest_feet.to_f * 12) + tallest_inches.to_f

      return self.height >= shortest_height_allowed_in_inches && self.height <= tallest_height_allowed_in_inches
    elsif (!shortest_feet.empty? && !shortest_inches.empty?)
      shortest_height_allowed_in_inches = (shortest_feet.to_f * 12) + shortest_inches.to_f

      return self.height >= shortest_height_allowed_in_inches
    elsif (!tallest_feet.empty? && !tallest_inches.empty?)
      tallest_height_allowed_in_inches = (tallest_feet.to_f * 12) + tallest_inches.to_f

      return self.height <= tallest_height_allowed_in_inches
    else # both empty
      return true
    end
  end

  def passes_through_weight_filters(lightest, heaviest)
    if !self.weight
      return true
    end

    if lightest.empty? && heaviest.empty?
      return true
    elsif lightest.empty?
      return self.weight <= heaviest.to_f
    elsif heaviest.empty?
      return self.weight >= lightest.to_f
    else
      return self.weight >= lightest.to_f && self.weight <= heaviest.to_f
    end
  end

  def passes_through_high_school_team_filters(high_school_team_ids_allowed)
    if !high_school_team_ids_allowed
      return true
    end

    return high_school_team_ids_allowed.include? self.high_school_team.id.to_s
  end

  def passes_through_club_team_filters(club_team_ids_allowed)
    if !club_team_ids_allowed
      return true
    end

    return club_team_ids_allowed.include? self.club_team.id.to_s
  end

  def passes_through_class_year_filters(class_years_allowed)
    if !class_years_allowed || class_years_allowed.empty?
      return true
    end

    if !self.class_year || self.class_year.empty?
      return true
    end

    return class_years_allowed.include? self.class_year
  end

  def passes_through_gpa_filters(smallest_gpa, largest_gpa)
    if !self.gpa
      return true
    end

    if smallest_gpa.empty? && largest_gpa.empty?
      return true
    elsif smallest_gpa.empty?
      return self.gpa <= largest_gpa.to_f
    elsif largest_gpa.empty?
      return self.gpa >= smallest_gpa.to_f
    else
      return self.gpa >= smallest_gpa.to_f && self.gpa <= largest_gpa.to_f
    end
  end

  def full_name
    if first_name && !first_name.empty? && last_name && !last_name.empty?
      return "#{first_name} #{last_name}"
    elsif first_name && !first_name.empty?
      return first_name
    elsif last_name && !last_name.empty?
      return last_name
    end
  end

  def full_name_with_middle
    "#{first_name} #{middle_name} #{last_name}"
  end

  def display_height
    if !height
      return nil
    end

    return "#{feet_component_of_height}\"#{inches_component_of_height}"
  end

  def feet_component_of_height
    if !height
      return nil
    else
      (height / 12).floor
    end
  end

  def inches_component_of_height
    if !height
      return nil
    else
      return (height % 12).to_i
    end
  end

  def positions
    result = position
    result += ", #{secondary_position}" if (secondary_position && !secondary_position.empty?)
    result += ", #{tertiary_position}" if (tertiary_position && !tertiary_position.empty?)

    return result
  end

  def age
    if !birthday
      nil
    else
      ((Date.current - birthday).to_f / 365).round(2)
    end
  end

  def current_user_notes(current_user)
    q = PlayerNote.where(player_id: self.id, user_id: current_user.id)

    q.empty? ? nil : q.first
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authorize_user, except: [:index, :show]
  helper_method :filter_params

  def index
    index_of_first_player = (page * Player.ITEMS_PER_PAGE) - Player.ITEMS_PER_PAGE
    index_of_last_player = page * Player.ITEMS_PER_PAGE

    @filter_options = Player.filter_options
    @filters_to_apply = players_table_filter_params && !players_table_filter_params.empty?
    @players = Player.sorted_players(players_table_sort_column, sort_direction)
    @players = @filters_to_apply ? get_filtered_players(@players, players_table_filter_params) : @players
    @num_filtered_players = @players.length
    @curr_page = page
    @players = @players[index_of_first_player...index_of_last_player]
  end

  def show
    @player = Player.find(params[:id])

    if @player.current_user_notes(current_user)
      @player_note = @player.current_user_notes(current_user)
    else
      @player_note = PlayerNote.new
    end
  end

  def new
    @player = Player.new
    @player.address = Address.new
  end

  def edit
    @player = Player.find(params[:id])
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to @player
    else
      render 'new'
    end
  end

  def update
    @player = Player.find(params[:id])

    if @player.update(player_params)
      redirect_to @player
    else
      render 'edit'
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    redirect_to players_path
  end

  private
    def player_params
      params_for_player = params
        .require(:player)
        .permit(:first_name, :middle_name, :last_name, :feet_component_of_height, :inches_component_of_height, :weight, :position, :secondary_position, :tertiary_position, :birthday, :high_school_team_id, :club_team_id, :gpa, :sat_score, :psat_score, :act_score, :class_year, :intended_major, :email, :phone_number, :notes, address_attributes: [ :id, :line_one, :line_two, :city, :state, :zip ])

      if params_for_player[:feet_component_of_height].empty? || params_for_player[:inches_component_of_height].empty?
        params_for_player[:height] = nil
      else
        params_for_player[:height] = (params_for_player[:feet_component_of_height].to_i * 12) + params_for_player[:inches_component_of_height].to_i
      end

      return params_for_player.except(:feet_component_of_height, :inches_component_of_height)
    end

    def filter_params
      players_table_filter_params
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_with model: @player do |f| %>
  <section class="card">
    <section class="card-header">
      Name
    </section>
    <section class="card-body">
      <section class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control" %>
      </section>
      <section class="form-group">
        <%= f.label :middle_name %>
        <%= f.text_field :middle_name, class: "form-control" %>
      </section>
      <section class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control" %>
      </section>
    </section>
  </section>
  <section class="card">
    <section class="card-header">
      Athletic
    </section>
    <section class="card-body">
      <section class="form-group">
        <%= f.label "Height (feet)" %>
        <%= f.number_field :feet_component_of_height, class: "form-control", in: 3..7 %>
      </section>
      <section class="form-group">
        <%= f.label "Height (inches)" %>
        <%= f.number_field :inches_component_of_height, class: "form-control", in: 0..11.5, step: 0.5 %>
      </section>
      <section class="form-group">
        <%= f.label :weight, "Weight (lbs)" %>
        <%= f.number_field :weight, class: "form-control", in: 60..400, step: 5 %>
      </section>
      <section class="form-group">
        <%= f.label :birthday %>
        <%= f.date_field :birthday, class: "form-control" %>
      </section>
      <section class="form-group">
        <%= f.label :position %>
        <%= f.text_field :position, class: "form-control" %>
      </section>
      <section class="form-group">
        <%= f.label :secondary_position %>
        <%= f.text_field :secondary_position, class: "form-control" %>
      </section>
      <section class="form-group">
        <%= f.label :tertiary_position %>
        <%= f.text_field :tertiary_position, class: "form-control" %>
      </section>
      <section class="form-group">
        <%= f.label :high_school_team %>
        <%= f.collection_select(:high_school_team_id, HighSchoolTeam.all, :id, :full_name, { include_blank: true }, class: "form-control") %>
      </section>
      <section class="form-group">
        <%= f.label :club_team %>
        <%= f.collection_select(:club_team_id, ClubTeam.all, :id, :name, { include_blank: true }, class: "form-control") %>
      </section>
    </section>
  </section>

  <section class="card">
    <section class="card-header">
      Academic
    </section>
    <section class="card-body">
      <section class="form-group">
        <%= f.label :class_year %>
        <%= f.select(:class_year, ['Freshman', 'Sophomore', 'Junior', 'Senior'], { include_blank: true }, class: "form-control") %>
      </section>
      <section class="form-group">
        <%= f.label :gpa, "GPA" %>
        <%= f.number_field :gpa, class: "form-control", in: 0..4, step: 0.05 %>
      </section>
      <section class="form-group">
        <%= f.label :sat_score, "SAT" %>
        <%= f.number_field :sat_score, class: "form-control", in: 400..1600, step: 10 %>
      </section>
      <section class="form-group">
        <%= f.label :psat_score, "PSAT" %>
        <%= f.number_field :psat_score, class: "form-control", in: 400..1600, step: 10 %>
      </section>
      <section class="form-group">
        <%= f.label :act_score, "ACT" %>
        <%= f.number_field :act_score, class: "form-control", in: 1..36, step: 1 %>
      </section>
      <section class="form-group">
        <%= f.label :intended_major %>
        <%= f.text_field :intended_major, class: "form-control" %>
      </section>
    </section>
  </section>

  <section class="card">
    <section class="card-header">
      Contact
    </section>
    <section class="card-body">
      <section class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </section>
      <section class="form-group">
        <%= f.label :phone_number %>
        <%= f.phone_field :phone_number, class: "form-control" %>
      </section>
      <%= render "shared/address_form", f: f %>
    </section>
  </section>
  <section class="card">
    <section class="card-header">
      Notes
    </section>
    <section class="card-body">
      <%= f.rich_text_area :notes, class: "form-control" %>
    </section>
  </section>


  <section class="form-group">
    <%= f.submit nil, class: "btn btn-primary" %>
  </section>
<% end %>

app/views/players/_table.html.erb
<section class="players-table row">
  <section class="col-lg-3">
    <section class="card bg-light filters">
      <section class="card-header">
        Filters
      </section>
      <section class="card-body">
        <%= form_with url: filters_url, method: :get, local: true do |f| %>
          <%= hidden_field_tag 'sort', params[:sort] if params[:sort] %>
          <%= hidden_field_tag 'direction', params[:direction] if params[:direction] %>
          <%= hidden_field_tag 'page', params[:page] if params[:page] %>
          <section class="filter-category height">
            <span>Height</span>
            <section class="form-group">
              <%= f.label :shortest %>
              <%= f.number_field :shortest_feet, value: params[:shortest_feet], class: "form-control", in: 3..7, placeholder: "ft" %>
              <%= f.number_field :shortest_inches, value: params[:shortest_inches], class: "form-control", in: 0..11.5, step: 0.5, placeholder: "in" %>
            </section>
            <section class="form-group">
              <%= f.label :tallest %>
              <%= f.number_field :tallest_feet, value: params[:tallest_feet], class: "form-control", in: 3..7, placeholder: "ft" %>
              <%= f.number_field :tallest_inches, value: params[:tallest_inches], class: "form-control", in: 0..11.5, step: 0.5, placeholder: "in" %>
            </section>
          </section>
          <section class="filter-category">
            <span>Weight</span>
            <section class="form-group">
              <%= f.label :lightest %>
              <%= f.number_field :lightest, value: params[:lightest], class: "form-control", in: 60..400, step: 5 %>
            </section>
            <section class="form-group">
              <%= f.label :heaviest %>
              <%= f.number_field :heaviest, value: params[:heaviest], class: "form-control", in: 60..400, step: 5 %>
            </section>
          </section>
          <section class="filter-category">
            <span>Class years</span>
            <% @filter_options[:class_years].each do |class_year| %>
              <section class="form-check">
                <label class="form-check-label">
                  <%= f.check_box "class_year_filters[]", { class: "form-check-input", checked: !@filters_to_apply || params[:class_year_filters].try(:include?, class_year) }, class_year, nil %>
                  <%= class_year %>
                </label>
              </section>
            <% end %>
          </section>
          <section class="filter-category">
            <span>GPA</span>
            <section class="form-group">
              <%= f.label :smallest %>
              <%= f.number_field :smallest_gpa, value: params[:smallest_gpa], class: "form-control", in: 0..4, step: 0.05 %>
            </section>
            <section class="form-group">
              <%= f.label :largest %>
              <%= f.number_field :largest_gpa, value: params[:largest_gpa], class: "form-control", in: 0..4, step: 0.05 %>
            </section>
          </section>
          <% if !excludes.include?(:high_school_team) && !@filter_options[:high_school_teams].empty? %>
            <section class="filter-category filter-category-fixed-height">
              <span>High school teams</span>
              <% @filter_options[:high_school_teams].each do |high_school_team| %>
                <section class="form-check">
                  <label class="form-check-label">
                    <%= f.check_box "high_school_team_filters[]", { class: "form-check-input", checked: !@filters_to_apply || params[:high_school_team_filters].try(:include?, high_school_team.id.to_s) }, high_school_team.id, nil %>
                    <%= high_school_team.full_name %>
                  </label>
                </section>
              <% end %>
            </section>
          <% end %>
          <% if !excludes.include?(:club_team) && !@filter_options[:club_teams].empty? %>
            <section class="filter-category filter-category-fixed-height">
              <span>Club teams</span>
              <% @filter_options[:club_teams].each do |club_team| %>
                <section class="form-check">
                  <label class="form-check-label">
                    <%= f.check_box "club_team_filters[]", { class: "form-check-input", checked: !@filters_to_apply || params[:club_team_filters].try(:include?, club_team.id.to_s) }, club_team.id, nil %>
                    <%= club_team.full_name %>
                  </label>
                </section>
              <% end %>
            </section>
          <% end %>
          <hr>
          <%= submit_tag "Apply filters", class: "btn btn-secondary btn-block" %>
        <% end %>
      </section>
    </section>
  </section>
  <section class="col-lg-9">
    <table class="table table-hover">
      <tr>
        <th><%= sortable "first_name", sort_column, sort_direction, "Name" %></th>
        <th><%= sortable "height", sort_column, sort_direction %></th>
        <th><%= sortable "weight", sort_column, sort_direction %></th>
        <% if !excludes.include? :high_school_team %>
          <th><%= sortable "high_school_team", sort_column, sort_direction, "High school team" %></th>
        <% end %>
        <% if !excludes.include? :club_team %>
          <th><%= sortable "club_team", sort_column, sort_direction, "Club team" %></th>
        <% end %>
        <th><%= sortable "class_year", sort_column, sort_direction, "Class year" %></th>
        <th><%= sortable "gpa", sort_column, sort_direction, "GPA" %></th>
        <% if is_admin? %>
          <th>Edit</th>
          <th>Delete</th>
        <% end %>
      </tr>

      <% players.each do |player| %>
        <tr>
          <td><%= link_to player.full_name, player_path(player) %></td>
          <td><%= player.display_height %></td>
          <td><%= player.weight %></td>
          <% if !excludes.include? :high_school_team %>
            <td><%= link_to player.high_school_team.full_name, high_school_team_path(player.high_school_team) if player.high_school_team %></td>
          <% end %>
          <% if !excludes.include? :club_team %>
            <td><%= link_to player.club_team.full_name, club_team_path(player.club_team) if player.club_team %></td>
          <% end %>
          <td><%= player.class_year %></td>
          <td><%= player.gpa %></td>
          <% if is_admin? %>
            <td><%= link_to "Edit", edit_player_path(player) %></td>
            <td><%= link_to 'Delete', player_path(player),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
    <% if paginate %>
      <%= render "shared/pagination", curr_page: curr_page, num_pages: (num_filtered_players / Player.ITEMS_PER_PAGE).ceil %>
    <% end %>
   </section>
</section>

app/views/players/edit.html.erb
<h1 class="page-header">Edit player</h1>

<%= render 'form' %>

app/views/players/index.html.erb
<h1 class="page-header">Players</h1>

<p><%= link_to "Export as spreadsheet", new_export_path %></p>
<% if is_admin? %>
  <p><%= link_to "Create a new player", new_player_path, class: "btn btn-primary" %></p>
<% end %>

<%= render "table", players: @players, paginate: true, curr_page: @curr_page, num_filtered_players: @num_filtered_players, filters_url: players_path, excludes: [], sort_column: players_table_sort_column, sort_direction: sort_direction %>

app/views/players/new.html.erb
<h1 class="page-header">Create a player</h1>

<%= render 'form' %>

app/views/players/show.html.erb
<h1 class="page-header"><%= @player.full_name_with_middle %></h1>

<section class="card">
  <section class="card-header">
    Athletic
  </section>
  <ul class="list-group">
    <li class="list-group-item">
      <strong>Height:</strong>
      <%= @player.display_height %>
    </li>
    <li class="list-group-item">
      <strong>Weight:</strong>
      <%= @player.weight %>
    </li>
    <li class="list-group-item">
      <strong>Age:</strong>
      <%= @player.age %>
    </li>
    <li class="list-group-item">
      <strong>Position:</strong>
      <%= @player.positions %>
    </li>
    <li class="list-group-item">
      <strong>High school:</strong>
      <%= link_to @player.high_school_team.full_name, high_school_team_path(@player.high_school_team) if @player.try(:high_school_team).try(:school_name) %>
    </li>
    <li class="list-group-item">
      <strong>Club team:</strong>
      <%= link_to @player.club_team.name, club_team_path(@player.club_team) if @player.club_team.try(:name) %>
    </li>
  </ul>
</section>

<section class="card">
  <section class="card-header">
    Academic
  </section>
  <ul class="list-group">
    <li class="list-group-item">
      <strong>Class year:</strong>
      <%= @player.class_year %>
    </li>
    <li class="list-group-item">
      <strong>GPA:</strong>
      <%= @player.gpa %>
    </li>
    <li class="list-group-item">
      <strong>SAT:</strong>
      <%= @player.sat_score %>
    </li>
    <li class="list-group-item">
      <strong>PSAT:</strong>
      <%= @player.psat_score %>
    </li>
    <li class="list-group-item">
      <strong>ACT:</strong>
      <%= @player.act_score %>
    </li>
    <li class="list-group-item">
      <strong>Intended major:</strong>
      <%= @player.intended_major %>
    </li>
  </ul>
</section>

<section class="card">
  <section class="card-header">
    Contact
  </section>
  <ul class="list-group">
    <li class="list-group-item">
      <strong>Email:</strong>
      <%= mail_to @player.email %>
    </li>
    <li class="list-group-item">
      <strong>Phone number:</strong>
      <%= @player.phone_number %>
    </li>
    <li class="list-group-item">
      <strong>Address:</strong>
      <%= render 'shared/address', address: @player.address %>
    </li>
  </ul>
</section>

<section class="card">
  <section class="card-header">
    Notes
  </section>
  <section class="card-body">
    <%= @player.notes %>
  </section>
</section>

<section class="card">
  <section class="card-header">
    My notes
  </section>
  <section class="card-body">
    <%= form_with model: @player_note, url: [@player, @player_note] do |f| %>
      <%= f.rich_text_area :notes, class: "form-control" %><br>
      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </section>
</section>

<%= link_to 'Edit', edit_player_path if is_admin? %>