config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations', passwords: 'users/passwords', registrations: 'users/registrations', sessions: 'users/sessions', unlocks: 'users/unlocks' }
  root 'home#index'

  authenticate :user do
    get '/search', to: 'search#search'

    resources :players do
      resources :player_notes
    end
    resources :high_school_teams
    resources :club_teams
    resources :tournaments
    resources :fields
    resources :games, only: [:new, :show, :edit, :update]
    resources :player_lists
    resources :exports, only: [:new, :create]
  end
end

app/models/field.rb
class Field < ApplicationRecord
  has_many :games, dependent: :destroy
  has_one :address, as: :addressable, dependent: :destroy

  accepts_nested_attributes_for :address, allow_destroy: true

  def self.search(query)
    if query
      where("lower(name) LIKE ?", "%#{query.downcase}%")
    else
      all
    end
  end

  def self.sorted_fields(sort_column, sort_direction)
    if sort_column === "location"
      return self.all.left_joins(:address).order("addresses.city #{sort_direction}")
    else
      fields_with_attr = self.where("#{sort_column} IS NOT NULL")
      fields_without_attr = self.where("#{sort_column} IS NULL")
      return fields_with_attr.order("#{sort_column} #{sort_direction}") + fields_without_attr
    end
  end

  def location
    if !address.city
      return ""
    end

    return "#{address.city}, #{address.state}"
  end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :authorize_user, except: [:index, :show]
  helper_method :sort_column

  def index
    @fields = Field.sorted_fields(sort_column, sort_direction)
  end

  def show
    @field = Field.find(params[:id])
  end

  def new
    @field = Field.new
    @field.address = Address.new
  end

  def edit
    @field = Field.find(params[:id])
  end

  def create
    @field = Field.new(field_params)

    if @field.save
      redirect_to @field
    else
      render 'new'
    end
  end

  def update
    @field = Field.find(params[:id])

    if @field.update(field_params)
      redirect_to @field
    else
      render 'edit'
    end
  end

  def destroy
    @field = Field.find(params[:id])
    @field.destroy

    redirect_to fields_path
  end

  private
    def field_params
      params
        .require(:field)
        .permit(:name, address_attributes: [ :id, :line_one, :line_two, :city, :state, :zip ])
    end

    def sort_column
      %w[name location].include?(params[:sort]) ? params[:sort] : "location"
    end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_form.html.erb
<%= form_with model: @field do |f| %>
  <section class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </section>

  <section class="card">
    <section class="card-header">
      Address
    </section>
    <section class="card-body">
      <%= render "shared/address_form", f: f %>
    </section>
  </section>
  <%= f.submit nil, class: "btn btn-primary" %>
<% end %>

app/views/fields/edit.html.erb
<h1 class="page-header">Edit field</h1>

<%= render 'form' %>

app/views/fields/index.html.erb
<h1 class="page-header">Fields</h1>

<p><%= link_to "Create a new field", new_field_path, class: "btn btn-primary" if is_admin? %></p>

<table class="table table-hover">
  <tr>
    <th><%= sortable "name", sort_column, sort_direction %></th>
    <th><%= sortable "location", sort_column, sort_direction %></th>
    <% if is_admin? %>
      <th>Edit</th>
      <th>Delete</th>
    <% end %>
  </tr>

  <% @fields.each do |field| %>
    <tr>
      <td><%= link_to field.name, field_path(field) %></td>
      <td><%= field.location %></td>
      <% if is_admin? %>
        <td><%= link_to "Edit", edit_field_path(field) %></td>
        <td><%= link_to 'Delete', field_path(field),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/fields/new.html.erb
<h1 class="page-header">Create a field</h1>

<%= render 'form' %>

app/views/fields/show.html.erb
<h1 class="page-header">Field page</h1>

<section class="card">
  <section class="card-header">
    Info
  </section>
  <ul class="list-group">
    <li class="list-group-item">
      <strong>Name:</strong>
      <%= @field.name %>
    </li>
    <li class="list-group-item">
      <strong>Address:</strong>
      <%= render 'shared/address', address: @field.address %>
    </li>
  </ul>
</section>

<section class="card">
  <section class="card-header">
    Games
  </section>
  <ul class="list-group">
    <% @field.games.each do |game| %>
      <li class="list-group-item"><%= link_to game.long_name, game_path(game) %></li>
    <% end %>
  </ul>
</section>

<%= link_to 'Edit', edit_field_path if is_admin? %>